language: elixir

elixir:
  - '1.8.2'

env:
  - MIX_ENV="test"

script:
  - mix compile --warnings-as-errors
  - mix coveralls.html
  - mix credo
  - mix format --check-formatted --dry-run
  - mix dialyzer --halt-exit-status

cache:
  directories:
    - _build
    - deps
